const SUPABASE_URL="https://qahksphurzoojashjfyj.supabase.co";
const SUPABASE_KEY="sb_publishable_zLxtcpAM-eTXRiV_8n8zrQ_PoZEp5pD";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let session=null,profile=null,companyId=null,currentPage="dashboard",products=[],cart=[];
async function init(){const {data:{session:s}}=await sb.auth.getSession();session=s;if(session)await enterApp();else $("#login").classList.remove("hidden");sb.auth.onAuthStateChange(async(_e,s)=>{session=s;if(s)await enterApp()})}
async function enterApp(){$("#login").classList.add("hidden");$("#app").classList.remove("hidden");const {data,error}=await sb.from("users").select("id,company_id,full_name,email,role_id,branch_id,roles(name)").eq("auth_user_id",session.user.id).single();if(error){$("#content").innerHTML=`<div class=card><h2>First-time Owner Setup</h2><p>Your Supabase login is valid, but the CHOIX ERP Owner profile has not been created yet.</p><button class=primary onclick="bootstrapOwner()">Create CHOIX ERP Owner Profile</button><div id=bootstrapMsg class=msg></div></div>`;return}profile=data;companyId=data.company_id;$("#userInfo").textContent=`${data.full_name||data.email} · ${data.roles?.name||""}`;await loadPage("dashboard")}
async function loadPage(p){currentPage=p;$("#pageTitle").textContent=p==="pos"?"My POS / Sale":p==="users"?"Users & Roles":p.replaceAll("_"," ");$$("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===p));const m={dashboard,pos,customers,products:productsPage,inventory,purchases,suppliers,membership,hr,accounts,reports,users,purchaseEntry,customerDue,supplierDue,accountTransactions,customerLedger,supplierLedger,expenseEntry,advancedReports,accountingSettings};await(m[p]||dashboard)()}
$$('#nav button').forEach(b=>b.onclick=()=>loadPage(b.dataset.page));$("#logout").onclick=async()=>{await sb.auth.signOut();location.reload()};$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginMsg").textContent="Signing in...";const {error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error)$("#loginMsg").textContent=error.message};
$("#setupOwnerBtn").onclick=async()=>{const email=$("#email").value.trim(),password=$("#password").value,fullName=prompt("Owner full name:","Mahadi");if(!email||!password||!fullName)return;$("#loginMsg").textContent="Creating Auth account...";const {data,error}=await sb.auth.signUp({email,password});if(error){$("#loginMsg").textContent=error.message;return}if(data.session){const r=await sb.rpc("bootstrap_first_owner",{p_full_name:fullName});if(r.error){$("#loginMsg").textContent=r.error.message;return}$("#loginMsg").textContent="Owner setup complete. Opening ERP...";return}$("#loginMsg").textContent="Account created. Check your email to confirm, then Login. The first login will show the Owner Setup button."};
async function bootstrapOwner(){const name=prompt("Owner full name:","Mahadi");if(!name)return;$("#bootstrapMsg").textContent="Creating Owner profile...";const {data,error}=await sb.rpc("bootstrap_first_owner",{p_full_name:name});if(error){$("#bootstrapMsg").textContent=error.message;return}$("#bootstrapMsg").textContent="Owner profile created. Loading ERP...";await enterApp();}
function stat(l,v){return `<div class=card stat-card><div class=muted>${l}</div><div class=stat>${typeof v==="number"?v.toLocaleString():v||"0"}</div></div>`}
async function dashboard(){
 const [{data:d,error:e},{data:rs},{data:tp},{data:cd},{data:sd}]=await Promise.all([sb.rpc("get_erp_dashboard"),sb.from("v_dashboard_recent_sales").select("*").order("sale_date",{ascending:false}).limit(8),sb.from("v_dashboard_top_products").select("*").limit(8),sb.from("v_customer_due_summary").select("name,phone,due_amount").gt("due_amount",0).order("due_amount",{ascending:false}).limit(6),sb.from("v_supplier_due_summary").select("name,phone,due_amount").gt("due_amount",0).order("due_amount",{ascending:false}).limit(6)]);
 if(e){$("#content").innerHTML=`<div class=card>${e.message}</div>`;return} const x=d||{};
 const money=v=>Number(v||0).toLocaleString()+" BDT";
 $("#content").innerHTML=`<div class="welcome"><div><div class="muted">Business Overview</div><h2>Good to see you, ${profile?.full_name||"User"} 👋</h2><p class=muted>Real-time sales, inventory, dues and operations at a glance.</p></div><button class=primary onclick="loadPage('pos')">Open POS</button></div>
 <div class=grid>${stat("Today's Sales",money(x.today_sales))}${stat("Orders",x.today_orders)}${stat("Collected",money(x.today_collected))}${stat("Sales Due",money(x.today_due))}${stat("Customer Due",money(x.customer_due))}${stat("Supplier Due",money(x.supplier_due))}${stat("Low Stock",x.low_stock_count)}${stat("Products",x.product_count)}</div>
 <div class=grid2><div class=card><div class=section-head><h3>Recent Sales</h3><button onclick="salesHistory()">View all</button></div>${renderTable(rs,null)}</div><div class=card><div class=section-head><h3>Top Products</h3></div>${renderTable(tp,null)}</div></div>
 <div class=grid2><div class=card><div class=section-head><h3>Customer Dues</h3><button onclick="loadPage('customerDue')">View dues</button></div>${renderTable(cd,null)}</div><div class=card><div class=section-head><h3>Supplier Dues</h3><button onclick="loadPage('supplierDue')">View dues</button></div>${renderTable(sd,null)}</div></div>`;
}
async function customers(){const {data,error}=await sb.from("customers").select("id,customer_code,name,phone,email,address,opening_due,is_active").limit(300);tablePage("Customers",data,error,true,customerForm)}
async function productsPage(){
 const {data,error}=await sb.from("products").select("id,sku,barcode,name,purchase_price,selling_price,vat_percent,reorder_level,color_group,is_active").order("name").limit(500);
 if(error)return tablePage("Products",data,error);
 const rows=(data||[]).map(r=>({...r,action:`<button onclick=printProductLabels('${r.id}')>🖨 Labels</button>`}));
 $("#content").innerHTML=`<div class="toolbar"><h2>Products</h2><button class=primary onclick=productForm()>+ Add New</button><button onclick=printAllProductLabels()>🖨 Print Labels</button><input placeholder="Search..." oninput=filterTable(this.value)></div>${renderTable(rows,null)}`;
}
async function suppliers(){const {data,error}=await sb.from("suppliers").select("id,supplier_code,name,phone,email,address,opening_due,is_active").limit(300);tablePage("Suppliers",data,error,true,supplierForm)}
async function inventory(){const [s,t,a,w]=await Promise.all([sb.from("v_stock_balance").select("*").limit(500),sb.from("stock_transfers").select("id,transfer_no,from_warehouse_id,to_warehouse_id,status,transfer_date,notes").order("created_at",{ascending:false}).limit(100),sb.from("stock_adjustments").select("id,adjustment_no,warehouse_id,status,reason,created_at").order("created_at",{ascending:false}).limit(100),sb.from("warehouses").select("id,name,is_active").eq("is_active",true)]);$("#content").innerHTML=`<div class=tabs><button class=primary onclick="transferForm()">+ Stock Transfer</button><button onclick="adjustmentForm()">+ Stock Adjustment</button><button onclick="lowStock()">Low Stock</button></div><div class=card><h2>Warehouse Stock</h2>${renderTable(s.data,s.error)}</div><div class=grid2><div class=card><h3>Recent Transfers</h3>${renderTable(t.data,t.error,"transfer")}</div><div class=card><h3>Recent Adjustments</h3>${renderTable(a.data,a.error)}</div></div>`;window._warehouses=w.data||[]}
async function lowStock(){const {data,error}=await sb.from("v_low_stock").select("*").limit(300);modal("Low Stock",renderTable(data,error))}
async function purchases(){const {data,error}=await sb.from("purchases").select("id,invoice_no,purchase_date,status,total_amount,paid_amount,due_amount,supplier_id").order("purchase_date",{ascending:false}).limit(300);if(error)return tablePage("Purchases",data,error);const rows=(data||[]).map(r=>({...r,action:r.status==='POSTED'?`<button onclick="purchaseReturnForm('${r.id}')">Return</button>`:''}));tablePage("Purchases",rows,null,false);$("#content").insertAdjacentHTML("afterbegin",`<div class=tabs><button class=primary onclick="purchaseEntry()">+ Purchase Entry / Goods Receive</button><button onclick="supplierDue()">Supplier Due / Payment</button></div>`);}

async function salesHistory(){const {data,error}=await sb.from("sales").select("id,invoice_no,sale_date,status,payment_status,total_amount,paid_amount,due_amount,customer_id").order("sale_date",{ascending:false}).limit(300);if(error)return tablePage("Sales / Invoices",data,error);const rows=(data||[]).map(r=>({...r,action:r.status==='POSTED'?`<button onclick="saleReturnForm('${r.id}')">Return</button> <button onclick="printInvoice('${r.id}')">Print</button>`:''}));tablePage("Sales / Invoices",rows,null,false);}

async function hr(){const {data,error}=await sb.from("employees").select("employee_code,full_name,phone,designation,basic_salary,status").limit(300);tablePage("Employees",data,error)}
async function accounts(){const {data,error}=await sb.from("accounts").select("id,account_code,account_name,account_type,is_system,is_active").limit(300);if(error)return tablePage("Accounts",data,error);tablePage("Accounts",data,null,true,journalForm)}
async function accountTransactions(){const {data,error}=await sb.from("v_accounts_ledger").select("journal_no,journal_date,account_code,account_name,debit,credit,description,line_description").order("journal_date",{ascending:false}).limit(500);tablePage("Account Transactions",data,error)}

async function reports(){const {data,error}=await sb.from("v_daily_sales_summary").select("*").limit(120);tablePage("Sales Reports",data,error)}
async function customerLedger(){const {data,error}=await sb.from("v_customer_ledger").select("customer_id,name,phone,transaction_type,reference_no,transaction_date,debit,credit,description").order("transaction_date",{ascending:false}).limit(800);tablePage("Customer Ledger",data,error)}
async function supplierLedger(){const {data,error}=await sb.from("v_supplier_ledger").select("supplier_id,name,phone,transaction_type,reference_no,transaction_date,debit,credit,description").order("transaction_date",{ascending:false}).limit(800);tablePage("Supplier Ledger",data,error)}
async function expenseEntry(){const [a,p,b]=await Promise.all([sb.from("accounts").select("id,account_code,account_name").eq("is_active",true).limit(500),sb.from("payment_accounts").select("id,name").eq("is_active",true),sb.from("branches").select("id,name").eq("is_active",true)]);modal("Expense Entry",`<form onsubmit="saveExpense(event)"><div class=form-grid><select id=ex_branch>${(b.data||[]).map(x=>`<option value=${x.id}>${x.name}</option>`).join("")}</select><select id=ex_account required><option value="">Expense Account</option>${(a.data||[]).map(x=>`<option value=${x.id}>${x.account_code} - ${x.account_name}</option>`).join("")}</select><select id=ex_payment required><option value="">Payment Account</option>${(p.data||[]).map(x=>`<option value=${x.id}>${x.name}</option>`).join("")}</select><input id=ex_amount type=number min=.01 step=.01 placeholder="Amount" required><input id=ex_desc placeholder="Description"></div><button class=primary>Post Expense</button></form>`)}
async function saveExpense(e){e.preventDefault();const {data,error}=await sb.rpc("create_expense",{p_branch_id:$("#ex_branch").value||null,p_expense_account_id:$("#ex_account").value,p_payment_account_id:$("#ex_payment").value,p_amount:Number($("#ex_amount").value),p_description:$("#ex_desc").value||null,p_expense_date:new Date().toISOString()});if(error)return alert(error.message);closeModal();accountTransactions();alert("Expense posted: "+data)}
async function advancedReports(){const {data,error}=await sb.rpc("get_erp_advanced_dashboard",{p_from:new Date(Date.now()-29*86400000).toISOString().slice(0,10),p_to:new Date().toISOString().slice(0,10)});if(error)return tablePage("Advanced Reports",null,error);const x=data||{};const money=v=>Number(v||0).toLocaleString()+" BDT";$("#content").innerHTML=`<div class=grid>${stat("Net Sales",money(x.net_sales))}${stat("Purchases",money(x.purchases))}${stat("Sales Returns",money(x.sales_returns))}${stat("Purchase Returns",money(x.purchase_returns))}${stat("Expenses",money(x.expenses))}${stat("Customer Due",money(x.customer_due))}${stat("Supplier Due",money(x.supplier_due))}${stat("Low Stock",x.low_stock)}</div><div class=grid2><div class=card><h3>Period Summary</h3>${renderTable([x],null)}</div><div class=card><h3>Quick Actions</h3><div class=tabs><button onclick="loadPage('customerLedger')">Customer Ledger</button><button onclick="loadPage('supplierLedger')">Supplier Ledger</button><button onclick="expenseEntry()">+ Expense</button></div></div></div>`}
async function accountingSettings(){const {data:a}=await sb.from("accounts").select("id,account_code,account_name,account_type").eq("is_active",true).limit(500);const {data:s}=await sb.from("erp_accounting_settings").select("*").maybeSingle();const opts=(sel)=>`<option value="">Not configured</option>`+(a||[]).map(x=>`<option value=${x.id} ${x.id===s?.[sel]?'selected':''}>${x.account_code} - ${x.account_name}</option>`).join("");modal("Automatic Accounting Setup",`<form onsubmit="saveAccountingSettings(event)"><p class=muted>Map ERP transactions to your chart of accounts. Automatic journals will use these mappings.</p><div class=form-grid>${[["inventory_account_id","Inventory"],["cogs_account_id","COGS"],["sales_account_id","Sales Revenue"],["purchase_account_id","Purchase"],["customer_receivable_account_id","Customer Receivable"],["supplier_payable_account_id","Supplier Payable"],["sales_return_account_id","Sales Return"],["purchase_return_account_id","Purchase Return"]].map(([k,l])=>`<label>${l}<select id="as_${k}">${opts(k)}</select></label>`).join("")}</div><button class=primary>Save Accounting Mapping</button></form>`)}
async function saveAccountingSettings(e){e.preventDefault();const g=k=>$("#as_"+k).value||null;const {error}=await sb.rpc("upsert_accounting_settings",{p_inventory_account_id:g("inventory_account_id"),p_cogs_account_id:g("cogs_account_id"),p_sales_account_id:g("sales_account_id"),p_purchase_account_id:g("purchase_account_id"),p_customer_receivable_account_id:g("customer_receivable_account_id"),p_supplier_payable_account_id:g("supplier_payable_account_id"),p_sales_return_account_id:g("sales_return_account_id"),p_purchase_return_account_id:g("purchase_return_account_id")});if(error)return alert(error.message);closeModal();alert("Accounting mapping saved")}

async function membership(){const [m,a,r]=await Promise.all([sb.from("v_customer_memberships").select("*").limit(300),sb.from("membership_applications").select("id,customer_id,tier_id,status,branch_id,created_at,rejection_reason").eq("status","PENDING").order("created_at",{ascending:false}).limit(100),sb.from("reward_transactions").select("membership_id,transaction_type,points,notes,created_at").order("created_at",{ascending:false}).limit(100)]);$("#content").innerHTML=`<div class=card><h2>Active Members</h2>${renderTable(m.data,m.error)}</div><div class=card><h2>Pending Applications</h2>${renderTable(a.data,a.error,"application")}</div><div class=card><h2>Recent Points History</h2>${renderTable(r.data,r.error)}</div>`}
async function users(){
 const [u,r,b]=await Promise.all([sb.from("users").select("id,full_name,username,email,phone,is_active,branch_id,roles(name)").limit(300),sb.from("roles").select("id,name,description,is_system_role").limit(100),sb.from("branches").select("id,name").eq("is_active",true)]);
 window._roles=r.data||[];window._branches=b.data||[];if(u.error)return tablePage("Users & Roles",u.data,u.error);
 const active=(u.data||[]).filter(x=>x.is_active).length;
 $("#content").innerHTML=`<div class="section-head"><div><h2>Users & Roles</h2><div class="muted">Control who can log in, which role they use, and which branch they belong to.</div></div><button class="primary" onclick="userForm()">+ Add User</button></div>
 <div class="grid">${stat("Total Users",(u.data||[]).length)}${stat("Active Users",active)}${stat("Roles",(r.data||[]).length)}${stat("Branches",(b.data||[]).length)}</div>
 <div class="grid2"><div class="card"><div class="section-head"><h3>System Responsibility</h3><span class="pill">Owner Controlled</span></div><p class="muted">Login emails, user access and role assignment should be maintained by the CHOIX ERP Owner/Admin. Technical database, security and software updates are handled through the ERP backend.</p><div class="tabs"><button onclick="userForm()">Create User</button><button onclick="roleInfo()">Role Guide</button></div></div><div class="card"><h3>Roles</h3>${renderTable(r.data,null)}</div></div>
 <div class="card"><div class="section-head"><h3>ERP Users</h3><input class="user-filter" placeholder="Search user / email / role" oninput="filterTable(this.value)"></div>${renderTable((u.data||[]).map(x=>({...x,role:x.roles?.name||'',status:x.is_active?'Active':'Inactive'})),null)}</div>`;
} 
function roleInfo(){modal("CHOIX ERP Role Guide",`<div class="role-guide"><div><b>Owner</b><span>Full company, finance, users and system control.</span></div><div><b>Admin / Manager</b><span>Daily operations, approvals and assigned management access.</span></div><div><b>Warehouse</b><span>Stock, receive, transfer and inventory operations.</span></div><div><b>Sales / POS</b><span>Customer sales and POS operations according to assigned permissions.</span></div><div><b>HR / Accounts</b><span>Use the relevant modules according to assigned permissions.</span></div></div>`)}
function userForm(){modal("Create ERP User",`<form onsubmit="saveUser(event)" class=form-grid><input id=u_name placeholder="Full name" required><input id=u_email type=email placeholder="Login email" required><input id=u_pass type=password placeholder="Temporary password" minlength=8 required><input id=u_username placeholder="Username"><input id=u_phone placeholder="Phone"><select id=u_role required>${(window._roles||[]).map(r=>`<option value="${r.id}">${r.name}</option>`).join("")}</select><select id=u_branch><option value="">No branch</option>${(window._branches||[]).map(b=>`<option value="${b.id}">${b.name}</option>`).join("")}</select><button class=primary style="grid-column:1/-1">Create User</button></form>`)}
async function saveUser(e){e.preventDefault();const {data,error}=await sb.functions.invoke("erp-create-user",{body:{email:$("#u_email").value,password:$("#u_pass").value,full_name:$("#u_name").value,username:$("#u_username").value||null,phone:$("#u_phone").value||null,role_id:$("#u_role").value,branch_id:$("#u_branch").value||null}});if(error)return alert(error.message);if(data?.error)return alert(data.error);closeModal();users()}

function renderTable(data,error,type){if(error)return `<p class=error>${error.message}</p>`;if(!data?.length)return `<p class=muted>No records yet.</p>`;const cols=Object.keys(data[0]);return `<div class=table-wrap><table class=table><thead><tr>${cols.filter(c=>c!=="action").map(c=>`<th>${c}</th>`).join("")}${type||data.some(r=>r.action)?"<th>Action</th>":""}</tr></thead><tbody>${data.map(r=>`<tr>${cols.filter(c=>c!=="action").map(c=>`<td>${fmt(r[c])}</td>`).join("")}${type==="transfer"?`<td>${r.status==="DRAFT"?`<button onclick="approveTransfer('${r.id}')">Approve</button>`:r.status==="APPROVED"?`<button onclick="receiveTransfer('${r.id}')">Receive</button>`:""}</td>`:type==="application"?`<td><button onclick="approveMember('${r.id}','${r.tier_id}')">Approve</button> <button onclick="rejectMember('${r.id}')">Reject</button></td>`:r.action?`<td>${r.action}</td>`:""}</tr>`).join("")}</tbody></table></div>`} 
function tablePage(title,data,error,canAdd=false,formFn=null){if(error){$("#content").innerHTML=`<div class=card>${error.message}</div>`;return}$("#content").innerHTML=`<div class=toolbar><h2>${title}</h2>${canAdd?`<button class=primary onclick="${formFn.name}()">+ Add New</button>`:""}<input placeholder="Search..." oninput="filterTable(this.value)"></div>${renderTable(data,error)}`}
function filterTable(q){q=q.toLowerCase();$$(".table tbody tr").forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?"":"none")}
function fmt(v){if(v==null)return"";if(typeof v==='boolean')return v?'Yes':'No';if(typeof v==='object')return JSON.stringify(v);return String(v)}
function modal(title,html){$("#content").insertAdjacentHTML("afterbegin",`<div id=modal class=modal><div class=modal-card><div class=modal-head><h2>${title}</h2><button onclick=closeModal()>×</button></div>${html}</div></div>`)}function closeModal(){$("#modal")?.remove()}
function customerForm(){modal("Add Customer",`<form onsubmit="saveCustomer(event)" class=form-grid><input id=c_name placeholder="Customer name" required><input id=c_phone placeholder="Phone"><input id=c_email placeholder="Email"><input id=c_address placeholder="Address"><input id=c_limit type=number step=.01 placeholder="Credit limit"><input id=c_due type=number step=.01 placeholder="Opening due"><button class=primary style="grid-column:1/-1">Save Customer</button></form>`)}
async function saveCustomer(e){e.preventDefault();const {error}=await sb.rpc("create_customer",{p_name:$("#c_name").value,p_phone:$("#c_phone").value,p_email:$("#c_email").value,p_address:$("#c_address").value,p_credit_limit:Number($("#c_limit").value||0),p_opening_due:Number($("#c_due").value||0)});if(error)return alert(error.message);closeModal();customers()}
async function productForm(){
 const [c,b,u]=await Promise.all([sb.from('categories').select('id,name,parent_id').eq('is_active',true).order('name'),sb.from('brands').select('id,name').eq('is_active',true).order('name'),sb.from('units').select('id,name').eq('is_active',true).order('name')]);
 modal("Add Product",`<form onsubmit="saveProduct(event)" class=form-grid><input id=p_name placeholder="Product name" required><input id=p_sku placeholder="SKU" required><input id=p_barcode placeholder="Barcode (blank = auto generate)"><select id=p_category><option value="">Category</option>${(c.data||[]).map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select><select id=p_brand><option value="">Brand</option>${(b.data||[]).map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select><select id=p_unit><option value="">Unit</option>${(u.data||[]).map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select><input id=p_color placeholder="Color Group"><input id=p_buy type=number step=.01 placeholder="Purchase price"><input id=p_sell type=number step=.01 placeholder="Selling price" required><input id=p_vat type=number step=.01 placeholder="VAT %"><input id=p_reorder type=number step=.01 placeholder="Reorder level"><button class=primary style="grid-column:1/-1">Save Product & Generate Barcode</button></form>`)}
async function saveProduct(e){e.preventDefault();const {data,error}=await sb.rpc("create_product",{p_name:$("#p_name").value,p_sku:$("#p_sku").value,p_barcode:$("#p_barcode").value||null,p_category_id:$("#p_category").value||null,p_brand_id:$("#p_brand").value||null,p_unit_id:$("#p_unit").value||null,p_purchase_price:Number($("#p_buy").value||0),p_selling_price:Number($("#p_sell").value||0),p_vat_percent:Number($("#p_vat").value||0),p_reorder_level:Number($("#p_reorder").value||0),p_color_group:$("#p_color").value||null});if(error)return alert(error.message);closeModal();productsPage();toast('Product saved. Barcode is ready for printing.')}
function supplierForm(){modal("Add Supplier",`<form onsubmit="saveSupplier(event)" class=form-grid><input id=s_name placeholder="Supplier name" required><input id=s_phone placeholder="Phone"><input id=s_email placeholder="Email"><input id=s_address placeholder="Address"><input id=s_due type=number step=.01 placeholder="Opening due"><button class=primary style="grid-column:1/-1">Save Supplier</button></form>`)}
async function saveSupplier(e){e.preventDefault();const {error}=await sb.rpc("create_supplier",{p_name:$("#s_name").value,p_phone:$("#s_phone").value,p_email:$("#s_email").value,p_address:$("#s_address").value,p_opening_due:Number($("#s_due").value||0)});if(error)return alert(error.message);closeModal();suppliers()}
async function transferForm(){if(!window._warehouses)await inventory();const ps=await sb.from("products").select("id,name,sku").eq("is_active",true).limit(500);products=ps.data||[];modal("Create Stock Transfer",`<form onsubmit="saveTransfer(event)"><div class=form-grid><select id=tr_from required>${window._warehouses.map(w=>`<option value=${w.id}>From: ${w.name}</option>`).join("")}</select><select id=tr_to required>${window._warehouses.map(w=>`<option value=${w.id}>To: ${w.name}</option>`).join("")}</select><select id=tr_product required>${products.map(p=>`<option value=${p.id}>${p.name} ${p.sku||""}</option>`).join("")}</select><input id=tr_qty type=number min=.01 step=.01 placeholder="Quantity" required><input id=tr_cost type=number step=.01 placeholder="Unit cost"><input id=tr_notes placeholder="Notes"><button class=primary style="grid-column:1/-1">Create Transfer</button></div></form>`)}
async function saveTransfer(e){e.preventDefault();const items=[{product_id:$("#tr_product").value,quantity:Number($("#tr_qty").value),unit_cost:Number($("#tr_cost").value||0)}];const {error}=await sb.rpc("create_stock_transfer",{p_from_warehouse_id:$("#tr_from").value,p_to_warehouse_id:$("#tr_to").value,p_items:items,p_notes:$("#tr_notes").value});if(error)return alert(error.message);closeModal();inventory()}
async function approveTransfer(id){const {error}=await sb.rpc("approve_stock_transfer",{p_transfer_id:id});if(error)alert(error.message);else inventory()}async function receiveTransfer(id){const {error}=await sb.rpc("receive_stock_transfer",{p_transfer_id:id});if(error)alert(error.message);else inventory()}
async function adjustmentForm(){if(!window._warehouses)await inventory();const ps=await sb.from("products").select("id,name,sku").eq("is_active",true).limit(500);products=ps.data||[];modal("Stock Adjustment",`<form onsubmit="saveAdjustment(event)"><div class=form-grid><select id=ad_wh required>${window._warehouses.map(w=>`<option value=${w.id}>${w.name}</option>`).join("")}</select><select id=ad_product required>${products.map(p=>`<option value=${p.id}>${p.name} ${p.sku||""}</option>`).join("")}</select><select id=ad_type><option value=IN>Adjustment In</option><option value=OUT>Adjustment Out</option><option value=DAMAGE>Damage</option><option value=CONSUMPTION>Consumption</option></select><input id=ad_qty type=number min=.01 step=.01 placeholder="Quantity" required><input id=ad_cost type=number step=.01 placeholder="Unit cost"><input id=ad_reason placeholder="Reason"><button class=primary style="grid-column:1/-1">Post Adjustment</button></div></form>`)}
async function saveAdjustment(e){e.preventDefault();const {error}=await sb.rpc("create_stock_adjustment",{p_warehouse_id:$("#ad_wh").value,p_items:[{product_id:$("#ad_product").value,quantity:Number($("#ad_qty").value),adjustment_type:$("#ad_type").value,unit_cost:Number($("#ad_cost").value||0)}],p_reason:$("#ad_reason").value,p_notes:null});if(error)return alert(error.message);closeModal();inventory()}
async function approveMember(id,tier){const {error}=await sb.rpc("approve_customer_membership",{p_application_id:id,p_tier_id:tier});if(error)alert(error.message);else membership()}async function rejectMember(id){const reason=prompt("Rejection reason:");const {error}=await sb.rpc("reject_customer_membership",{p_application_id:id,p_reason:reason||null});if(error)alert(error.message);else membership()}
async function saleReturnForm(id){const {data,error}=await sb.from("v_invoice_details").select("sale_item_id,product_id,product_name,quantity,unit_price,line_total").eq("sale_id",id);if(error)return alert(error.message);modal("Sale Return",`<form onsubmit="saveSaleReturn(event,'${id}')"><div class=table-wrap><table class=table><tr><th>Product</th><th>Sold</th><th>Return Qty</th></tr>${(data||[]).map((x,i)=>`<tr><td>${x.product_name}</td><td>${x.quantity}</td><td><input id="sr_${i}" data-item="${x.sale_item_id}" data-product="${x.product_id}" type=number min=0 step=.01 max="${x.quantity}" value=0></td></tr>`).join("")}</table></div><input id=sr_notes placeholder="Notes" style="margin-top:10px"><button class=primary style="margin-top:10px">Post Return</button></form>`);window._returnItems=data||[]}
async function saveSaleReturn(e,id){e.preventDefault();const items=window._returnItems.map((x,i)=>({sale_item_id:x.sale_item_id,product_id:x.product_id,quantity:Number($(`#sr_${i}`).value||0)})).filter(x=>x.quantity>0);if(!items.length)return alert("Select return quantity");const {error}=await sb.rpc("create_sale_return",{p_sale_id:id,p_items:items,p_notes:$("#sr_notes").value});if(error)return alert(error.message);closeModal();salesHistory()}
async function purchaseReturnForm(id){const {data,error}=await sb.from("purchase_items").select("id,product_id,quantity,unit_cost,batch_no,expiry_date,products(name)").eq("purchase_id",id);if(error)return alert(error.message);modal("Purchase Return",`<form onsubmit="savePurchaseReturn(event,'${id}')"><div class=table-wrap><table class=table><tr><th>Product</th><th>Purchased</th><th>Return Qty</th></tr>${(data||[]).map((x,i)=>`<tr><td>${x.products?.name||x.product_id}</td><td>${x.quantity}</td><td><input id="pr_${i}" data-item="${x.id}" data-product="${x.product_id}" type=number min=0 step=.01 max="${x.quantity}" value=0></td></tr>`).join("")}</table></div><input id=pr_notes placeholder="Notes" style="margin-top:10px"><button class=primary style="margin-top:10px">Post Return</button></form>`);window._purchaseReturnItems=data||[]}
async function savePurchaseReturn(e,id){e.preventDefault();const items=window._purchaseReturnItems.map((x,i)=>({purchase_item_id:x.id,product_id:x.product_id,quantity:Number($(`#pr_${i}`).value||0)})).filter(x=>x.quantity>0);if(!items.length)return alert("Select return quantity");const {error}=await sb.rpc("create_purchase_return",{p_purchase_id:id,p_items:items,p_notes:$("#pr_notes").value});if(error)return alert(error.message);closeModal();purchases()}
async function printInvoice(id){const {data,error}=await sb.from("v_invoice_details").select("*").eq("sale_id",id);if(error||!data?.length)return alert(error?.message||"Invoice not found");const h=data[0];const rows=data.map(x=>`<tr><td>${x.product_name}</td><td>${x.quantity}</td><td>${Number(x.unit_price).toLocaleString()}</td><td>${Number(x.line_total).toLocaleString()}</td></tr>`).join("");const w=window.open("","_blank","width=800,height=900");w.document.write(`<html><head><title>${h.invoice_no}</title><style>body{font-family:Arial;padding:30px}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border-bottom:1px solid #ddd;padding:10px;text-align:left}.total{text-align:right;font-size:18px;font-weight:bold}</style></head><body><h1>CHOIX ERP</h1><h3>Invoice: ${h.invoice_no}</h3><p>${new Date(h.sale_date).toLocaleString()}<br>Customer: ${h.customer_name||"Walk-in"} ${h.customer_phone||""}</p><table><tr><th>Product</th><th>Qty</th><th>Price</th><th>Total</th></tr>${rows}</table><p class=total>Grand Total: ${Number(h.total_amount).toLocaleString()} BDT</p><p>Paid: ${Number(h.paid_amount).toLocaleString()} BDT &nbsp; Due: ${Number(h.due_amount).toLocaleString()} BDT</p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
async function pos(){
 const [pr,br,wh,pm]=await Promise.all([
  sb.from("products").select("id,name,sku,barcode,selling_price,vat_percent,purchase_price,color_group,is_active,categories(name)").eq("is_active",true).order("name").limit(1000),
  sb.from("branches").select("id,name,code").eq("is_active",true).order("name"),
  sb.from("warehouses").select("id,name,branch_id").eq("is_active",true).order("name"),
  sb.from("payment_methods").select("id,name,code").eq("is_active",true).order("name")
 ]);
 products=pr.data||[];cart=[];window._posBranches=br.data||[];window._posWarehouses=wh.data||[];window._posPaymentMethods=pm.data||[];
 const inv="POS-"+Date.now();
 $("#content").innerHTML=`
 <div class="pos-header">
  <div><div class="muted">Retail Sales Terminal</div><h2>My POS / Sale</h2><div class="muted">Invoice, customer, stock and payment — all in one screen.</div></div>
  <div class="pos-actions"><button onclick="salesHistory()">Sales / Invoice History</button><button onclick="printLastPOSInvoice()">🖨 Print Last Invoice</button></div>
 </div>
 <div class="pos-meta card">
  <div class="form-grid">
   <label>Invoice No<input id="posInvoice" value="${inv}" readonly></label>
   <label>Date<input id="posDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label>
   <label>Branch<select id="posBranch" onchange="refreshPOSWarehouses()">${window._posBranches.map(x=>`<option value="${x.id}" ${x.id===profile?.branch_id?'selected':''}>${x.name}</option>`).join("")}</select></label>
   <label>Warehouse<select id="posWarehouse"></select></label>
  </div>
 </div>
 <div class="pos-layout">
  <div class="pos-main">
   <div class="card">
    <div class="section-head"><div><h3>Customer & Membership</h3><div class="muted">Phone works as Membership ID.</div></div><button onclick="newPOSCustomer()">+ New Customer</button></div>
    <div class="form-grid">
      <input id="posCustomerPhone" placeholder="Customer Phone / Membership ID" onblur="lookupPOSCustomer()" onkeydown="if(event.key==='Enter'){event.preventDefault();lookupPOSCustomer()}">
      <input id="posCustomerName" placeholder="Customer Name">
      <input id="posCustomerAddress" placeholder="Address">
      <input id="posCustomerEmail" type="email" placeholder="Email">
    </div>
    <div id="posCustomerInfo" class="member-banner muted">Walk-in customer</div>
   </div>
   <div class="card">
    <div class="section-head"><div><h3>Products</h3><div class="muted">Search by product, SKU or scan barcode.</div></div></div>
    <div class="pos-search"><input id="posSearch" placeholder="Search product / barcode / SKU" oninput="renderProducts()" onkeydown="scanPOSBarcode(event)" autofocus><button onclick="scanPOSBarcode({key:'Enter',preventDefault:()=>{}})">Add Barcode</button></div>
    <div id="productList" class="product-list"></div>
   </div>
   <div class="card">
    <div class="section-head"><h3>Sale Items</h3><span class="pill" id="posItemCount">0 Items</span></div>
    <div id="cart" class="pos-cart"></div>
   </div>
  </div>
  <div class="pos-side">
   <div class="card sticky-pos">
    <h3>Payment & Summary</h3>
    <div id="posSummary"></div>
    <div class="pos-pay-grid">
      <label>Discount<input id="posDiscount" type="number" min="0" step=".01" value="0" oninput="renderCart()"></label>
      
    </div>
    <label>Payment Method<select id="posPaymentMethod">${window._posPaymentMethods.map(x=>`<option value="${x.id}">${x.name}</option>`).join("")}</select></label>
    <label>Paid Amount<input id="posPaid" type="number" min="0" step=".01" value="0" oninput="renderCart()"></label>
    <label>Notes<textarea id="posNotes" rows="3" placeholder="Sale notes"></textarea></label>
    <div id="posMsg" class="msg"></div>
    <button class="primary pos-complete" onclick="checkout()">✓ Complete Sale & Print Invoice</button>
    <button class="secondary pos-clear" onclick="clearPOS()">Clear / New Sale</button>
   </div>
  </div>
 </div>`;
 refreshPOSWarehouses();renderProducts();renderCart();
}
function refreshPOSWarehouses(){const b=$("#posBranch")?.value;if(!b)return;$("#posWarehouse").innerHTML=(window._posWarehouses||[]).filter(x=>x.branch_id===b).map(x=>`<option value="${x.id}">${x.name}</option>`).join("")}
function scanPOSBarcode(e){if(e.key!=="Enter")return;e.preventDefault();const q=$("#posSearch").value.trim().toLowerCase();if(!q)return;const p=products.find(x=>String(x.barcode||'').toLowerCase()===q||String(x.sku||'').toLowerCase()===q);if(p){addCart(p.id);$("#posSearch").select();toast(`${p.name} added`)}else{$("#posMsg").textContent="Product barcode / SKU not found."}}
function renderProducts(){const q=($("#posSearch")?.value||"").toLowerCase();const list=products.filter(p=>(p.name+" "+(p.sku||"")+" "+(p.barcode||"")+" "+(p.color_group||"")).toLowerCase().includes(q)).slice(0,80);$("#productList").innerHTML=list.map(p=>`<button class="product-btn pos-product" onclick="addCart('${p.id}')"><b>${esc(p.name)}</b><span class="muted">${esc(p.categories?.name||p.color_group||'')} · ${esc(p.sku||'')}</span><span class="muted">Barcode: ${esc(p.barcode||'')}</span><strong>৳ ${Number(p.selling_price||0).toLocaleString()}</strong></button>`).join("")||`<div class="muted">No matching products.</div>`}
function addCart(id){const p=products.find(x=>x.id===id);if(!p)return;const x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({id:p.id,name:p.name,sku:p.sku,barcode:p.barcode,category:p.categories?.name||"",price:Number(p.selling_price||0),vat:Number(p.vat_percent||0),qty:1,discountPct:0});renderCart()}
function changeCartQty(i,v){const q=Math.max(0,Number(v||0));if(q===0)cart.splice(i,1);else cart[i].qty=q;renderCart()}
function changeCartDiscount(i,v){cart[i].discountPct=Math.max(0,Number(v||0));renderCart()}
function renderCart(){
 const sub=cart.reduce((s,x)=>s+(x.qty*x.price),0),lineDisc=cart.reduce((s,x)=>s+(x.qty*x.price*Number(x.discountPct||0)/100),0),disc=Math.max(0,Number($("#posDiscount")?.value||0))+lineDisc,total=Math.max(0,sub-disc),paid=Math.max(0,Number($("#posPaid")?.value||0)),due=Math.max(0,total-paid),change=Math.max(0,paid-total);
 $("#posItemCount")&&($("#posItemCount").textContent=cart.reduce((s,x)=>s+x.qty,0)+" Items");
 $("#cart").innerHTML=cart.length?`<div class="pos-table"><div class="pos-row pos-head"><span>Product</span><span>Qty</span><span>Price</span><span>Disc.</span><span>Total</span><span></span></div>${cart.map((x,i)=>`<div class="pos-row"><span><b>${esc(x.name)}</b><small>${esc(x.sku||'')} · ${esc(x.barcode||'')}</small></span><input type=number min=0 step=.01 value="${x.qty}" onchange="changeCartQty(${i},this.value)"><span>৳ ${x.price.toLocaleString()}</span><input type=number min=0 step=.01 value="${x.discountPct||0}" onchange="changeCartDiscount(${i},this.value)"><b>৳ ${(Math.max(0,x.qty*x.price-(x.qty*x.price*Number(x.discountPct||0)/100))).toLocaleString()}</b><button onclick="changeCartQty(${i},0)">×</button></div>`).join("")}</div>`:`<div class="empty-pos">No items added. Search or scan a barcode to start the sale.</div>`;
 $("#posSummary").innerHTML=`<div class="summary-line"><span>Subtotal</span><b>৳ ${sub.toLocaleString()}</b></div><div class="summary-line"><span>Discount</span><b>− ৳ ${disc.toLocaleString()}</b></div><div class="summary-total"><span>Grand Total</span><b>৳ ${total.toLocaleString()}</b></div><div class="summary-line"><span>Paid</span><b>৳ ${paid.toLocaleString()}</b></div><div class="summary-line"><span>Due</span><b>৳ ${due.toLocaleString()}</b></div>${change?`<div class="summary-line"><span>Change</span><b>৳ ${change.toLocaleString()}</b></div>`:''}`;
}
async function lookupPOSCustomer(){const phone=$("#posCustomerPhone")?.value.trim();if(!phone){$("#posCustomerInfo").textContent="Walk-in customer";return}const {data:c}=await sb.from("customers").select("id,name,phone,email,address").eq("phone",phone).limit(1);const customer=c?.[0];if(customer){$("#posCustomerName").value=customer.name||'';$("#posCustomerAddress").value=customer.address||'';$("#posCustomerEmail").value=customer.email||'';window._posCustomerId=customer.id;const {data:m}=await sb.rpc("lookup_membership_by_phone",{p_phone:phone});const mm=m?.[0];$("#posCustomerInfo").innerHTML=mm?`✓ Member: <b>${esc(mm.customer_name)}</b> · ${esc(mm.tier_name||'Member')} · ${mm.points_balance} points`:`Customer found · Not an active member`}
else{window._posCustomerId=null;$("#posCustomerInfo").textContent="New customer — name/address can be saved with the sale."}}
function newPOSCustomer(){["#posCustomerPhone","#posCustomerName","#posCustomerAddress","#posCustomerEmail"].forEach(s=>{if($(s))$(s).value=''});window._posCustomerId=null;$("#posCustomerInfo").textContent="New / Walk-in customer";$("#posCustomerPhone").focus()}
async function ensurePOSCustomer(){let id=window._posCustomerId||null;const name=$("#posCustomerName").value.trim(),phone=$("#posCustomerPhone").value.trim(),email=$("#posCustomerEmail").value.trim(),address=$("#posCustomerAddress").value.trim();if(id||(!name&&!phone))return id;if(phone){const {data:c}=await sb.from("customers").select("id").eq("phone",phone).limit(1);if(c?.[0]?.id)return c[0].id}if(!name)return null;const {data,error}=await sb.rpc("create_customer",{p_name:name,p_phone:phone||null,p_email:email||null,p_address:address||null,p_credit_limit:0,p_opening_due:0});if(error)throw error;return data?.id||data}
async function checkout(){
 if(!cart.length)return $("#posMsg").textContent="Add at least one product.";
 const branch=$("#posBranch").value,warehouse=$("#posWarehouse").value,pm=$("#posPaymentMethod").value;if(!branch||!warehouse)return $("#posMsg").textContent="Select branch and warehouse.";if(!pm)return $("#posMsg").textContent="Select a payment method.";
 const sub=cart.reduce((s,x)=>s+x.qty*x.price,0),lineDisc=cart.reduce((s,x)=>s+(x.qty*x.price*Number(x.discountPct||0)/100),0),discount=Math.max(0,Number($("#posDiscount").value||0))+lineDisc,total=Math.max(0,sub-discount),paid=Math.max(0,Number($("#posPaid").value||0));
 if(paid>total)return $("#posMsg").textContent="Paid amount cannot be greater than Grand Total.";
 try{const customer=await ensurePOSCustomer();const items=cart.map(x=>({product_id:x.id,quantity:x.qty,unit_price:x.price,discount_amount:Number(x.qty*x.price*Number(x.discountPct||0)/100)}));const payments=paid>0?[{payment_method_id:pm,amount:paid}]:[];const {data,error}=await sb.rpc("create_pos_sale",{p_branch_id:branch,p_warehouse_id:warehouse,p_invoice_no:$("#posInvoice").value,p_customer_id:customer,p_items:items,p_payments:payments,p_discount_amount:Math.max(0,Number($("#posDiscount").value||0)),p_notes:$("#posNotes").value||null});if(error)throw error;window._lastPOSInvoiceId=typeof data==='string'?data:data?.id||data?.sale_id;toast("Sale completed successfully");await printInvoice(window._lastPOSInvoiceId);clearPOS(false)}catch(err){$("#posMsg").textContent=err.message||String(err)}}
function clearPOS(show=true){cart=[];window._posCustomerId=null;$("#posInvoice")&&($("#posInvoice").value="POS-"+Date.now());["#posCustomerPhone","#posCustomerName","#posCustomerAddress","#posCustomerEmail","#posNotes"].forEach(s=>{if($(s))$(s).value=''});if($("#posDiscount"))$("#posDiscount").value=0;if($("#posPaid"))$("#posPaid").value=0;if(show)toast("New sale ready");renderCart()}
function printLastPOSInvoice(){if(window._lastPOSInvoiceId)printInvoice(window._lastPOSInvoiceId);else toast("No completed sale yet","error")}

function renderProducts(){const q=($("#posSearch")?.value||"").toLowerCase();$("#productList").innerHTML=products.filter(p=>(p.name+" "+(p.sku||"")+" "+(p.barcode||"")).toLowerCase().includes(q)).map(p=>`<button class=product-btn onclick="addCart('${p.id}')"><b>${p.name}</b><br><span class=muted>${p.sku||""}</span><br>${Number(p.selling_price).toLocaleString()} BDT</button>`).join("")}
function addCart(id){const p=products.find(x=>x.id===id),x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({id:p.id,name:p.name,price:Number(p.selling_price),qty:1});renderCart()}function renderCart(){let t=0;$("#cart").innerHTML=cart.map(x=>{let l=x.qty*x.price;t+=l;return `<div class=cart-row><span>${x.name} × ${x.qty}</span><b>${l.toLocaleString()}</b></div>`}).join("");$("#cartTotal").textContent=t.toLocaleString()+" BDT"}
async function lookupMember(){const phone=$("#memberPhone").value.trim();if(!phone)return;const {data,error}=await sb.rpc("lookup_membership_by_phone",{p_phone:phone});if(error)return $("#memberInfo").textContent=error.message;const m=data?.[0];$("#memberInfo").innerHTML=m?`✓ ${m.customer_name} · ${m.tier_name||"Member"} · ${m.points_balance} points`:`No active membership found`}
async function purchaseEntry(){
 const [br,wh,su,ps,pa]=await Promise.all([sb.from("branches").select("id,name").eq("is_active",true),sb.from("warehouses").select("id,name,branch_id").eq("is_active",true),sb.from("suppliers").select("id,name,phone").eq("is_active",true),sb.from("products").select("id,name,sku,purchase_price,vat_percent").eq("is_active",true).limit(500),sb.from("payment_accounts").select("id,name,account_kind").eq("is_active",true)]);
 window._purchaseData={branches:br.data||[],warehouses:wh.data||[],suppliers:su.data||[],products:ps.data||[],paymentAccounts:pa.data||[]};window._purchaseRows=[{product_id:"",quantity:1,unit_cost:0,discount_amount:0,vat_amount:0,batch_no:"",expiry_date:""}];
 modal("Purchase Entry / Goods Receive",`<form onsubmit="savePurchaseEntry(event)"><div class=form-grid><select id=pe_branch required onchange="refreshPurchaseWarehouses()">${window._purchaseData.branches.map(x=>`<option value=${x.id}>${x.name}</option>`).join("")}</select><select id=pe_wh required></select><select id=pe_supplier required>${window._purchaseData.suppliers.map(x=>`<option value=${x.id}>${x.name} ${x.phone||""}</option>`).join("")}</select><input id=pe_invoice placeholder="Purchase Invoice No" required><input id=pe_supplier_invoice placeholder="Supplier Invoice / GRN Ref"><select id=pe_pay>${window._purchaseData.paymentAccounts.map(x=>`<option value=${x.id}>${x.name}</option>`).join("")}</select><input id=pe_paid type=number min=0 step=.01 value=0 placeholder="Paid Amount"><input id=pe_notes placeholder="Notes"></div><div class=section-head style="margin-top:16px"><h3>Items</h3><button type=button onclick="addPurchaseRow()">+ Add Item</button></div><div id=pe_rows></div><button class=primary style="margin-top:14px">Post Purchase & Receive Stock</button></form>`);refreshPurchaseWarehouses();renderPurchaseRows();}
function refreshPurchaseWarehouses(){const b=$("#pe_branch")?.value;if(!b)return;$("#pe_wh").innerHTML=(window._purchaseData.warehouses||[]).filter(x=>x.branch_id===b).map(x=>`<option value=${x.id}>${x.name}</option>`).join("");}
function addPurchaseRow(){window._purchaseRows.push({product_id:"",quantity:1,unit_cost:0,discount_amount:0,vat_amount:0,batch_no:"",expiry_date:""});renderPurchaseRows();}
function renderPurchaseRows(){const ps=window._purchaseData.products||[];$("#pe_rows").innerHTML=window._purchaseRows.map((r,i)=>`<div class="purchase-row"><select onchange="purchaseRowChange(${i},'product_id',this.value)"><option value="">Product</option>${ps.map(p=>`<option value=${p.id} ${p.id===r.product_id?'selected':''}>${p.name} ${p.sku||''}</option>`).join('')}</select><input type=number min=.01 step=.01 value=${r.quantity} onchange="purchaseRowChange(${i},'quantity',this.value)" placeholder=Qty><input type=number min=0 step=.01 value=${r.unit_cost} onchange="purchaseRowChange(${i},'unit_cost',this.value)" placeholder=Cost><input type=number min=0 step=.01 value=${r.discount_amount} onchange="purchaseRowChange(${i},'discount_amount',this.value)" placeholder=Discount><input type=number min=0 step=.01 value=${r.vat_amount} onchange="purchaseRowChange(${i},'vat_amount',this.value)" placeholder=VAT><input value="${r.batch_no||''}" onchange="purchaseRowChange(${i},'batch_no',this.value)" placeholder=Batch><input type=date value="${r.expiry_date||''}" onchange="purchaseRowChange(${i},'expiry_date',this.value)"><button type=button onclick="removePurchaseRow(${i})">×</button></div>`).join("");}
function purchaseRowChange(i,k,v){window._purchaseRows[i][k]=['quantity','unit_cost','discount_amount','vat_amount'].includes(k)?Number(v||0):v;}
function removePurchaseRow(i){if(window._purchaseRows.length===1)return;window._purchaseRows.splice(i,1);renderPurchaseRows();}
async function savePurchaseEntry(e){e.preventDefault();const items=window._purchaseRows.filter(r=>r.product_id).map(r=>({...r}));if(!items.length)return alert("Add at least one product");const {data,error}=await sb.rpc("create_purchase_entry",{p_branch_id:$("#pe_branch").value,p_warehouse_id:$("#pe_wh").value,p_supplier_id:$("#pe_supplier").value,p_invoice_no:$("#pe_invoice").value,p_supplier_invoice_no:$("#pe_supplier_invoice").value||null,p_items:items,p_paid_amount:Number($("#pe_paid").value||0),p_payment_account_id:$("#pe_pay").value||null,p_notes:$("#pe_notes").value||null});if(error)return alert(error.message);const purchaseId=typeof data==='string'?data:data?.id||data?.purchase_id;closeModal();purchases();toast('Purchase received. Stock updated and barcode labels are ready.');if(purchaseId)setTimeout(()=>printPurchaseLabels(purchaseId),250)}
async function customerDue(){const {data,error}=await sb.from("v_customer_due_summary").select("customer_id,customer_code,name,phone,opening_due,due_amount").gt("due_amount",0).order("due_amount",{ascending:false}).limit(500);if(error)return tablePage("Customer Due",data,error);const rows=(data||[]).map(r=>({...r,action:`<button onclick="customerPaymentForm('${r.customer_id}','${String(r.name).replace(/'/g,"\\'")}','${r.due_amount}')">Collect</button>`}));tablePage("Customer Due / Payment",rows,null,false);}
async function supplierDue(){const {data,error}=await sb.from("v_supplier_due_summary").select("supplier_id,supplier_code,name,phone,opening_due,due_amount").gt("due_amount",0).order("due_amount",{ascending:false}).limit(500);if(error)return tablePage("Supplier Due",data,error);const rows=(data||[]).map(r=>({...r,action:`<button onclick="supplierPaymentForm('${r.supplier_id}','${String(r.name).replace(/'/g,"\\'")}','${r.due_amount}')">Pay</button>`}));tablePage("Supplier Due / Payment",rows,null,false);}
async function customerPaymentForm(id,name,due){const {data:pa}=await sb.from("payment_accounts").select("id,name").eq("is_active",true);modal("Collect Customer Due",`<form onsubmit="saveCustomerPayment(event,'${id}')"><p><b>${name}</b> · Outstanding: ${Number(due).toLocaleString()} BDT</p><div class=form-grid><input id=cp_amount type=number min=.01 max=${due} step=.01 placeholder="Amount" required><select id=cp_account><option value="">Payment account</option>${(pa||[]).map(x=>`<option value=${x.id}>${x.name}</option>`).join("")}</select><input id=cp_ref placeholder="Reference No"><input id=cp_notes placeholder="Notes"></div><button class=primary>Collect Payment</button></form>`)}
async function saveCustomerPayment(e,id){e.preventDefault();const {error}=await sb.rpc("create_customer_payment",{p_customer_id:id,p_amount:Number($("#cp_amount").value),p_payment_account_id:$("#cp_account").value||null,p_branch_id:profile?.branch_id||null,p_reference_no:$("#cp_ref").value||null,p_notes:$("#cp_notes").value||null});if(error)return alert(error.message);closeModal();customerDue();}
async function supplierPaymentForm(id,name,due){const {data:pa}=await sb.from("payment_accounts").select("id,name").eq("is_active",true);modal("Pay Supplier Due",`<form onsubmit="saveSupplierPayment(event,'${id}')"><p><b>${name}</b> · Outstanding: ${Number(due).toLocaleString()} BDT</p><div class=form-grid><input id=sp_amount type=number min=.01 max=${due} step=.01 placeholder="Amount" required><select id=sp_account><option value="">Payment account</option>${(pa||[]).map(x=>`<option value=${x.id}>${x.name}</option>`).join("")}</select><input id=sp_ref placeholder="Reference No"><input id=sp_notes placeholder="Notes"></div><button class=primary>Pay Supplier</button></form>`)}
async function saveSupplierPayment(e,id){e.preventDefault();const {error}=await sb.rpc("create_supplier_payment",{p_supplier_id:id,p_amount:Number($("#sp_amount").value),p_payment_account_id:$("#sp_account").value||null,p_branch_id:profile?.branch_id||null,p_reference_no:$("#sp_ref").value||null,p_notes:$("#sp_notes").value||null});if(error)return alert(error.message);closeModal();supplierDue();}
async function journalForm(){const {data:a}=await sb.from("accounts").select("id,account_code,account_name").eq("is_active",true).limit(500);window._accounts=a||[];window._journalRows=[{account_id:"",debit:0,credit:0,description:""},{account_id:"",debit:0,credit:0,description:""}];modal("New Journal Entry",`<form onsubmit="saveJournal(event)"><div class=form-grid><input id=j_no placeholder="Journal No" value="JV-${Date.now()}" required><input id=j_desc placeholder="Description"><input id=j_ref_type placeholder="Reference Type"><input id=j_ref_id placeholder="Reference ID"></div><div class=section-head style="margin-top:16px"><h3>Journal Lines</h3><button type=button onclick="addJournalRow()">+ Line</button></div><div id=j_rows></div><button class=primary>Post Journal</button></form>`);renderJournalRows();}
function addJournalRow(){window._journalRows.push({account_id:"",debit:0,credit:0,description:""});renderJournalRows();}
function renderJournalRows(){const a=window._accounts||[];$("#j_rows").innerHTML=window._journalRows.map((r,i)=>`<div class="journal-row"><select onchange="jChange(${i},'account_id',this.value)"><option value="">Account</option>${a.map(x=>`<option value=${x.id} ${x.id===r.account_id?'selected':''}>${x.account_code} - ${x.account_name}</option>`).join('')}</select><input type=number min=0 step=.01 value=${r.debit} onchange="jChange(${i},'debit',this.value)" placeholder=Debit><input type=number min=0 step=.01 value=${r.credit} onchange="jChange(${i},'credit',this.value)" placeholder=Credit><input value="${r.description||''}" onchange="jChange(${i},'description',this.value)" placeholder=Description></div>`).join("");}
function jChange(i,k,v){window._journalRows[i][k]=['debit','credit'].includes(k)?Number(v||0):v;}
async function saveJournal(e){e.preventDefault();const {data,error}=await sb.rpc("create_journal_entry",{p_branch_id:profile?.branch_id||null,p_journal_no:$("#j_no").value,p_description:$("#j_desc").value||null,p_lines:window._journalRows,p_reference_type:$("#j_ref_type").value||null,p_reference_id:$("#j_ref_id").value||null});if(error)return alert(error.message);closeModal();accountTransactions();alert("Journal posted: "+data);}
/* Barcode + label printing */
const EAN_L={0:'0001101',1:'0011001',2:'0010011',3:'0111101',4:'0100011',5:'0110001',6:'0101111',7:'0111011',8:'0110111',9:'0001011'};
const EAN_G={0:'0100111',1:'0110011',2:'0011011',3:'0100001',4:'0011101',5:'0111001',6:'0000101',7:'0010001',8:'0001001',9:'0010111'};
const EAN_R={0:'1110010',1:'1100110',2:'1101100',3:'1000010',4:'1011100',5:'1001110',6:'1010000',7:'1000100',8:'1001000',9:'1110100'};
const EAN_PARITY={0:'LLLLLL',1:'LLGLGG',2:'LLGGLG',3:'LLGGGL',4:'LGLLGG',5:'LGGLLG',6:'LGGGLL',7:'LGLGLG',8:'LGLGGL',9:'LGGLGL'};
function ean13Svg(raw){let d=String(raw||'').replace(/\D/g,'');if(d.length===12){let sum=0;for(let i=0;i<12;i++)sum+=Number(d[i])*(i%2?3:1);d+=String((10-sum%10)%10)}if(d.length!==13)return `<div class=barcode-fallback>${esc(raw||'')}</div>`;const first=Number(d[0]),par=EAN_PARITY[first];let bits='101';for(let i=0;i<6;i++)bits+=par[i]==='L'?EAN_L[d[i+1]]:EAN_G[d[i+1]];bits+='01010';for(let i=7;i<13;i++)bits+=EAN_R[d[i]];bits+='101';let rects='',x=8;for(const bit of bits){if(bit==='1')rects+=`<rect x="${x}" y="2" width="1" height="48"/>`;x++}return `<svg class=barcode-svg viewBox="0 0 ${x+8} 62" preserveAspectRatio="none" aria-label="Barcode"><g shape-rendering="crispEdges">${rects}</g><text x="${x/2}" y="60" text-anchor="middle" font-size="8" font-family="Arial">${d}</text></svg>`}
function labelCard(p){return `<div class=print-label><div class=label-brand>CHOIX</div><div class=label-name>${esc(p.name)}</div><div class=label-meta>${esc(p.color_group||'')} ${p.sku?`· ${esc(p.sku)}`:''}</div>${ean13Svg(p.barcode)}<div class=label-price>৳ ${Number(p.selling_price||0).toLocaleString()}</div></div>`}
function openPrintDialog(products,title='Barcode Labels'){
 const list=(products||[]).filter(Boolean);if(!list.length)return toast('No products selected','error');
 modal(title,`<div class=form-grid><label>Paper / Label Size<select id=print_size><option value="a4">A4 Sheet (30 labels)</option><option value="58">58mm × 30mm</option><option value="40">40mm × 25mm</option></select></label><label>Copies per product<input id=print_copies type=number min=1 max=500 value=1></label></div><p class=muted>For received quantity printing, choose the purchase option; it will use received quantity automatically.</p><div class=tabs><button class=primary onclick="runLabelPrint()">🖨 Print Labels</button><button onclick="closeModal()">Cancel</button></div><div class=card style="margin-top:12px">${list.map(p=>`<div style="display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #eee"><span>${esc(p.name)} · ${esc(p.barcode||'')}</span><b>৳ ${Number(p.selling_price||0).toLocaleString()}</b></div>`).join('')}</div>`);window._labelProducts=list}
function runLabelPrint(){const size=$('#print_size').value,copies=Math.max(1,Number($('#print_copies').value||1)),items=[];for(const p of (window._labelProducts||[]))for(let i=0;i<copies;i++)items.push(p);printLabelsWindow(items,size)}
function printLabelsWindow(items,size='a4'){
 const win=window.open('','_blank','width=1000,height=800');if(!win)return alert('Please allow pop-ups for CHOIX ERP to print labels.');
 const pageClass=size==='a4'?'a4':size==='58'?'label58':'label40';win.document.write(`<!doctype html><html><head><title>CHOIX Barcode Labels</title><style>@page{size:${size==='a4'?'A4':size==='58'?'58mm 30mm':'40mm 25mm'};margin:${size==='a4'?'8mm':'0'}}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif}.sheet{display:grid;grid-template-columns:${size==='a4'?'repeat(3,1fr)': '1fr'};gap:${size==='a4'?'5mm':'0'};align-content:start}.print-label{width:${size==='a4'?'58mm':size==='58'?'58mm':'40mm'};height:${size==='a4'?'30mm':size==='58'?'30mm':'25mm'};padding:2mm;text-align:center;overflow:hidden;border:1px dashed #bbb}.label-brand{font-weight:800;font-size:9px;letter-spacing:1px}.label-name{font-weight:700;font-size:${size==='40'?'7px':'8px'};white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:1px}.label-meta{font-size:6px;height:8px;overflow:hidden}.barcode-svg{width:90%;height:${size==='40'?'11mm':'13mm'};display:block;margin:0 auto}.label-price{font-size:${size==='40'?'9px':'11px'};font-weight:800}.barcode-fallback{font-size:8px;font-weight:700;margin:5px}.sheet{width:100%}@media print{.print-label{break-inside:avoid}} </style></head><body><div class="sheet">${items.map(labelCard).join('')}</div><script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);win.document.close()}
async function printProductLabels(id){const {data,error}=await sb.from('products').select('id,name,sku,barcode,selling_price,color_group').eq('id',id).single();if(error)return toast(error.message,'error');openPrintDialog([data],`Print Labels · ${data.name}`)}
async function printAllProductLabels(){const {data,error}=await sb.from('products').select('id,name,sku,barcode,selling_price,color_group').eq('is_active',true).order('name').limit(500);if(error)return toast(error.message,'error');openPrintDialog(data,'Print Product Labels')}
async function printPurchaseLabels(purchaseId){const {data,error}=await sb.from('purchase_items').select('quantity,product_id,products(id,name,sku,barcode,selling_price,color_group)').eq('purchase_id',purchaseId);if(error)return toast(error.message,'error');const items=[];for(const r of (data||[])){const p=r.products;if(!p)continue;const n=Math.min(500,Math.max(1,Math.round(Number(r.quantity||1))));for(let i=0;i<n;i++)items.push(p)}if(!items.length)return toast('No received products found','error');openPrintDialog(items,'Received Goods · Barcode Labels')}

init();

/* CHOIX ERP v7 UX + reporting layer */
function toast(message,type='success'){let t=document.createElement('div');t.className='toast '+type;t.textContent=message;document.body.appendChild(t);setTimeout(()=>t.classList.add('show'),10);setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),250)},2800)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function advancedReports(){
 const from=new Date(Date.now()-29*86400000).toISOString().slice(0,10),to=new Date().toISOString().slice(0,10);
 await advancedReportsRange(from,to);
}
async function advancedReportsRange(from,to){
 const {data,error}=await sb.rpc('get_erp_advanced_dashboard',{p_from:from,p_to:to});
 if(error){$('#content').innerHTML=`<div class=card error>${esc(error.message)}</div>`;return}
 const x=data||{}, money=v=>Number(v||0).toLocaleString()+' BDT';
 $('#content').innerHTML=`<div class="section-head"><div><h2>Advanced Dashboard</h2><div class="muted">Financial and operational summary</div></div><div class="report-filter"><label>From <input id="ar_from" type="date" value="${from}"></label><label>To <input id="ar_to" type="date" value="${to}"></label><button class="primary" onclick="advancedReportsRange($('#ar_from').value,$('#ar_to').value)">Apply</button></div></div>
 <div class="metric-grid">${stat('Net Sales',money(x.net_sales))}${stat('Purchases',money(x.purchases))}${stat('Expenses',money(x.expenses))}${stat('Stock Value',money(x.stock_value))}${stat('Sales Returns',money(x.sales_returns))}${stat('Purchase Returns',money(x.purchase_returns))}${stat('Customer Due',money(x.customer_due))}${stat('Supplier Due',money(x.supplier_due))}</div>
 <div class="grid2"><div class="card"><h3>Period Summary</h3>${renderTable([x],null)}</div><div class="card"><h3>Accounting</h3><div class="tabs"><button onclick="trialBalance()">Trial Balance</button><button onclick="profitLoss()">Profit & Loss</button><button onclick="backfillJournals()">Backfill Journals</button></div><p class="muted">Automatic journals are created from mapped transactions. Backfill is for older posted transactions.</p></div></div>`;
}
async function trialBalance(){const {data,error}=await sb.from('v_trial_balance').select('account_code,account_name,account_type,total_debit,total_credit,balance').order('account_code').limit(500);tablePage('Trial Balance',data,error)}
async function profitLoss(){const {data,error}=await sb.from('v_profit_loss_summary').select('account_type,account_code,account_name,net_balance').order('account_type').order('account_code').limit(500);tablePage('Profit & Loss Summary',data,error)}
async function backfillJournals(){if(!confirm('Create missing automatic journals for existing posted sales and purchases?'))return;const {data,error}=await sb.rpc('backfill_automatic_journals');if(error)return toast(error.message,'error');toast(`Backfill processed ${data?.processed||0} transaction(s)`);advancedReports()}
async function reports(){const {data,error}=await sb.from('v_daily_sales_summary').select('*').order('sale_date',{ascending:false}).limit(365);if(error)return tablePage('Sales Reports',data,error);$('#content').innerHTML=`<div class="section-head"><div><h2>Sales Reports</h2><div class="muted">Daily posted sales</div></div><button class="primary" onclick="advancedReports()">Advanced Dashboard</button></div>${renderTable(data,null)}`}
async function customerLedger(){const {data,error}=await sb.from('v_customer_ledger').select('customer_id,name,phone,transaction_type,reference_no,transaction_date,debit,credit,description').order('transaction_date',{ascending:false}).limit(1000);if(error)return tablePage('Customer Ledger',data,error);tablePage('Customer Ledger',data,null);}
async function supplierLedger(){const {data,error}=await sb.from('v_supplier_ledger').select('supplier_id,name,phone,transaction_type,reference_no,transaction_date,debit,credit,description').order('transaction_date',{ascending:false}).limit(1000);if(error)return tablePage('Supplier Ledger',data,error);tablePage('Supplier Ledger',data,null);}
