const SUPABASE_URL="https://qahksphurzoojashjfyj.supabase.co";
const SUPABASE_KEY="sb_publishable_zLxtcpAM-eTXRiV_8n8zrQ_PoZEp5pD";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let session=null,profile=null,companyId=null,currentPage="dashboard",products=[],cart=[],currentPermissions=[];
const CHOIX_APP_VERSION="2026.09.24.6";
async function checkAppVersion(){try{const r=await fetch("version.json?t="+Date.now(),{cache:"no-store"});const v=await r.json();if(v.version&&v.version!==CHOIX_APP_VERSION){const k="choix-reloaded-"+v.version;if(!sessionStorage.getItem(k)){sessionStorage.setItem(k,"1");location.reload(true);}}}catch(e){}}
async function init(){checkAppVersion();const {data:{session:s}}=await sb.auth.getSession();session=s;if(session)await enterApp();else $("#login").classList.remove("hidden");sb.auth.onAuthStateChange(async(_e,s)=>{session=s;if(s)await enterApp()})}
async function enterApp(){$("#login").classList.add("hidden");$("#app").classList.remove("hidden");const {data,error}=await sb.from("users").select("id,company_id,full_name,email,role_id,branch_id,roles(name)").eq("auth_user_id",session.user.id).single();if(error){$("#content").innerHTML=`<div class=card><h2>First-time Owner Setup</h2><p>Your Supabase login is valid, but the CHOIX ERP Owner profile has not been created yet.</p><button class=primary onclick="bootstrapOwner()">Create CHOIX ERP Owner Profile</button><div id=bootstrapMsg class=msg></div></div>`;return}profile=data;companyId=data.company_id;const pr=await sb.rpc("get_my_permissions");currentPermissions=pr.error?[]:(pr.data||[]);$("#userInfo").textContent=`${data.full_name||data.email} · ${data.roles?.name||""}`;await loadPage("dashboard")}
const PAGE_PERMISSIONS={dashboard:"dashboard.view",pos:"pos.use",customers:"customers.manage",products:"products.manage",inventory:"inventory.view",purchases:"purchase.create",suppliers:"suppliers.manage",membership:"membership.manage",hr:"hr.manage",accounts:"accounts.view",reports:"reports.view",users:"users.manage",purchaseEntry:"purchase.create",customerDue:"accounts.view",supplierDue:"accounts.view",accountTransactions:"accounts.view",customerLedger:"accounts.view",supplierLedger:"accounts.view",expenseEntry:"accounts.manage",advancedReports:"reports.view",accountingSettings:"accounts.manage"};
function canAccess(page){const p=PAGE_PERMISSIONS[page];return !p||profile?.roles?.name==="Owner"||currentPermissions.includes(p)}
async function loadPage(p){if(!canAccess(p)){toast("You do not have permission for this module","error");return}currentPage=p;$("#pageTitle").textContent=p==="pos"?"My POS / Sale":p==="users"?"Users & Roles":p.replaceAll("_"," ");$("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===p));const m={dashboard,pos,customers,products:productsPage,inventory,purchases,suppliers,membership,hr,accounts,reports,users,purchaseEntry,customerDue,supplierDue,accountTransactions,customerLedger,supplierLedger,expenseEntry,advancedReports,accountingSettings};try{await(m[p]||dashboard)()}catch(e){console.error(e);$("#content").innerHTML=`<div class="card error"><h3>Module Error</h3><p>${esc(e?.message||e)}</p></div>`}}
$$('#nav button').forEach(b=>b.onclick=()=>loadPage(b.dataset.page));$("#logout").onclick=async()=>{await sb.auth.signOut();location.reload()};$("#loginForm").onsubmit=async e=>{e.preventDefault();const msg=$("#loginMsg");msg.textContent="Signing in...";const email=$("#email").value.trim(),password=$("#password").value;if(!email||!password){msg.textContent="Email and password are required.";return}try{const r=await Promise.race([sb.auth.signInWithPassword({email,password}),new Promise((_,rej)=>setTimeout(()=>rej(new Error("Sign-in timed out. Please refresh and try again.")),15000))]);if(r.error){msg.textContent=r.error.message;return}if(r.data?.session){session=r.data.session;await enterApp()}}catch(err){console.error(err);msg.textContent=err?.message||"Sign-in failed."}};
$("#setupOwnerBtn").onclick=async()=>{const email=$("#email").value.trim(),password=$("#password").value,fullName=prompt("Owner full name:","Mahadi");if(!email||!password||!fullName)return;$("#loginMsg").textContent="Creating Auth account...";const {data,error}=await sb.auth.signUp({email,password});if(error){$("#loginMsg").textContent=error.message;return}if(data.session){const r=await sb.rpc("bootstrap_first_owner",{p_full_name:fullName});if(r.error){$("#loginMsg").textContent=r.error.message;return}$("#loginMsg").textContent="Owner setup complete. Opening ERP...";return}$("#loginMsg").textContent="Account created. Check your email to confirm, then Login. The first login will show the Owner Setup button."};
async function bootstrapOwner(){const name=prompt("Owner full name:","Mahadi");if(!name)return;$("#bootstrapMsg").textContent="Creating Owner profile...";const {data,error}=await sb.rpc("bootstrap_first_owner",{p_full_name:name});if(error){$("#bootstrapMsg").textContent=error.message;return}$("#bootstrapMsg").textContent="Owner profile created. Loading ERP...";await enterApp();}
function stat(l,v){return `<div class=card stat-card><div class=muted>${l}</div><div class=stat>${typeof v==="number"?v.toLocaleString():v||"0"}</div></div>`}
async function dashboard(){
 const today=new Date().toISOString().slice(0,10);
 const monthStart=new Date();monthStart.setDate(1);
 const [adv,low]=await Promise.all([
  sb.rpc("get_erp_advanced_dashboard",{p_from:monthStart.toISOString().slice(0,10),p_to:today}),
  sb.from("v_low_stock").select("*").limit(8)
 ]);
 if(adv.error)return $("#content").innerHTML=`<div class="card error">${esc(adv.error.message)}</div>`;
 const x=adv.data||{},money=v=>Number(v||0).toLocaleString()+" BDT";
 $("#content").innerHTML=`<div class="welcome"><div><div class="muted">Business Overview · This Month</div><h2>Good to see you, ${esc(profile?.full_name||"User")} 👋</h2><p class=muted>Sales, purchases, dues, stock and profit overview.</p></div><button class=primary onclick="loadPage('pos')">Open POS</button></div>
 <div class="grid">${stat("Net Sales",money(x.net_sales))}${stat("Purchases",money(x.purchases))}${stat("Expenses",money(x.expenses))}${stat("Stock Value",money(x.stock_value))}${stat("Customer Due",money(x.customer_due))}${stat("Supplier Due",money(x.supplier_due))}${stat("Low Stock",x.low_stock)}${stat("Sales Returns",money(x.sales_returns))}</div>
 <div class="grid2"><div class="card"><div class="section-head"><h3>Low Stock</h3><button onclick="lowStock()">View all</button></div>${renderTable(low.data,low.error)}</div><div class="card"><h3>Quick Actions</h3><div class=tabs><button onclick="loadPage('pos')">New Sale</button><button onclick="purchaseEntry()">Purchase</button><button onclick="customerDue()">Customer Due</button><button onclick="supplierDue()">Supplier Due</button></div></div></div>`;}
async function customers(){const {data,error}=await sb.from("customers").select("id,customer_code,name,phone,email,address,opening_due,is_active").limit(300);tablePage("Customers",data,error,true,customerForm)}
async function productsPage(){
 const {data,error}=await sb.from("products").select("id,sku,barcode,name,purchase_price,selling_price,vat_percent,reorder_level,color_group,is_active").order("name").limit(500);
 if(error)return tablePage("Products",data,error);
 const rows=(data||[]).map(r=>({...r,action:`<button onclick=printProductLabels('${r.id}')>🖨 Labels</button>`}));
 $("#content").innerHTML=`<div class="toolbar"><h2>Products</h2><button class=primary onclick=productForm()>+ Add New</button><button onclick=printAllProductLabels()>🖨 Print Labels</button><input placeholder="Search..." oninput=filterTable(this.value)></div>${renderTable(rows,null)}`;
}
async function suppliers(){const {data,error}=await sb.from("suppliers").select("id,supplier_code,name,phone,email,address,opening_due,is_active").limit(300);tablePage("Suppliers",data,error,true,supplierForm)}
async function inventory(){const [s,t,a,w]=await Promise.all([sb.from("v_stock_balance").select("*").limit(500),sb.from("stock_transfers").select("id,transfer_no,from_warehouse_id,to_warehouse_id,status,transfer_date,notes").order("created_at",{ascending:false}).limit(100),sb.from("stock_adjustments").select("id,adjustment_no,warehouse_id,status,reason,created_at").order("created_at",{ascending:false}).limit(100),sb.from("warehouses").select("id,name,is_active").eq("is_active",true)]);$("#content").innerHTML=`<div class=tabs><button class=primary onclick="transferForm()">+ Stock Transfer</button><button onclick="adjustmentForm()">+ Stock Adjustment</button><button onclick="lowStock()">Low Stock</button></div><div class=card><h2>Warehouse Stock</h2>${renderTable(s.data,s.error)}</div><div class=grid2><div class=card><h3>Recent Transfers</h3>${renderTable(t.data,t.error,"transfer")}</div><div class=card><h3>Recent Adjustments</h3>${renderTable(a.data,a.error)}</div></div>`;window._warehouses=w.data||[]}
async function lowStock(){const {data,error}=await sb.from("v_low_stock").select("*").limit(300);modal("Low Stock",renderTable(data,error))}
async function purchases(){const {data,error}=await sb.from("purchases").select("id,invoice_no,purchase_date,status,total_amount,paid_amount,due_amount,supplier_id").order("purchase_date",{ascending:false}).limit(300);if(error)return tablePage("Purchases",data,error);const rows=(data||[]).map(r=>({...r,action:r.status==='POSTED'?`<button onclick="purchaseReturnForm('${r.id}')">Return</button>`:''}));tablePage("Purchases",rows,null,false);$("#content").insertAdjacentHTML("afterbegin",`<div class=tabs><button class=primary onclick="purchaseEntry()">+ Purchase Entry / Goods Receive</button><button onclick="supplierDue()">Supplier Due / Payment</button></div>`);}

async function salesHistory(){const {data,error}=await sb.from("sales").select("id,invoice_no,sale_date,status,payment_status,total_amount,paid_amount,due_amount,customer_id").order("sale_date",{ascending:false}).limit(300);if(error)return tablePage("Sales / Invoices",data,error);const rows=(data||[]).map(r=>({...r,action:r.status==='POSTED'?`<button onclick="saleReturnForm('${r.id}')">Return</button> <button onclick="printInvoice('${r.id}')">Print</button>`:''}));tablePage("Sales / Invoices",rows,null,false);}

async function hr(){const {data,error}=await sb.from("employees").select("employee_code,full_name,phone,designation,basic_salary,status").limit(300);tablePage("Employees",data,error)}
async function accounts(){const {data,error}=await sb.from("accounts").select("id,account_code,account_name,account_type,is_system,is_active").limit(300);if(error)return tablePage("Accounts",data,error);tablePage("Accounts",data,null,true,journalForm)}
async function accountTransactions(){const {data,error}=await sb.from("v_accounts_ledger").select("journal_no,journal_date,account_code,account_name,debit,credit,description,line_description").order("journal_date",{ascending:false}).limit(500);tablePage("Account Transactions",data,error)}

async function customerLedger(){const {data,error}=await sb.from("v_customer_ledger").select("customer_id,name,phone,transaction_type,reference_no,transaction_date,debit,credit,description").order("transaction_date",{ascending:false}).limit(800);tablePage("Customer Ledger",data,error)}
async function supplierLedger(){const {data,error}=await sb.from("v_supplier_ledger").select("supplier_id,name,phone,transaction_type,reference_no,transaction_date,debit,credit,description").order("transaction_date",{ascending:false}).limit(800);tablePage("Supplier Ledger",data,error)}
async function expenseEntry(){const [a,p,b]=await Promise.all([sb.from("accounts").select("id,account_code,account_name").eq("is_active",true).limit(500),sb.from("payment_accounts").select("id,name").eq("is_active",true),sb.from("branches").select("id,name").eq("is_active",true)]);modal("Expense Entry",`<form onsubmit="saveExpense(event)"><div class=form-grid><select id=ex_branch>${(b.data||[]).map(x=>`<option value=${x.id}>${x.name}</option>`).join("")}</select><select id=ex_account required><option value="">Expense Account</option>${(a.data||[]).map(x=>`<option value=${x.id}>${x.account_code} - ${x.account_name}</option>`).join("")}</select><select id=ex_payment required><option value="">Payment Account</option>${(p.data||[]).map(x=>`<option value=${x.id}>${x.name}</option>`).join("")}</select><input id=ex_amount type=number min=.01 step=.01 placeholder="Amount" required><input id=ex_desc placeholder="Description"></div><button class=primary>Post Expense</button></form>`)}
async function saveExpense(e){e.preventDefault();const {data,error}=await sb.rpc("create_expense",{p_branch_id:$("#ex_branch").value||null,p_expense_account_id:$("#ex_account").value,p_payment_account_id:$("#ex_payment").value,p_amount:Number($("#ex_amount").value),p_description:$("#ex_desc").value||null,p_expense_date:new Date().toISOString()});if(error)return alert(error.message);closeModal();accountTransactions();alert("Expense posted: "+data)}
async function advancedReportsRange(from,to){
 const {data,error}=await sb.rpc('get_erp_advanced_dashboard',{p_from:from,p_to:to});
 if(error){$('#content').innerHTML=`<div class=card error>${esc(error.message)}</div>`;return}
 const x=data||{}, money=v=>Number(v||0).toLocaleString()+' BDT';
 $('#content').innerHTML=`<div class="section-head"><div><h2>Advanced Dashboard</h2><div class="muted">Financial and operational summary</div></div><div class="report-filter"><label>From <input id="ar_from" type="date" value="${from}"></label><label>To <input id="ar_to" type="date" value="${to}"></label><button class="primary" onclick="advancedReportsRange($('#ar_from').value,$('#ar_to').value)">Apply</button></div></div>
 <div class="metric-grid">${stat('Net Sales',money(x.net_sales))}${stat('Purchases',money(x.purchases))}${stat('Expenses',money(x.expenses))}${stat('Stock Value',money(x.stock_value))}${stat('Sales Returns',money(x.sales_returns))}${stat('Purchase Returns',money(x.purchase_returns))}${stat('Customer Due',money(x.customer_due))}${stat('Supplier Due',money(x.supplier_due))}</div>
 <div class="grid2"><div class="card"><h3>Period Summary</h3>${renderTable([x],null)}</div><div class="card"><h3>Accounting</h3><div class="tabs"><button onclick="trialBalance()">Trial Balance</button><button onclick="profitLoss()">Profit & Loss</button><button onclick="backfillJournals()">Backfill Journals</button></div><p class="muted">Automatic journals are created from mapped transactions. Backfill is for older posted transactions.</p></div></div>`;
}
async function trialBalance(){const {data,error}=await sb.from('v_trial_balance').select('account_code,account_name,account_type,total_debit,total_credit,balance').order('account_code').limit(500);tablePage('Trial Balance',data,error)}
async function profitLoss(){const {data,error}=await sb.from('v_profit_loss_summary').select('account_type,account_code,account_name,net_balance').order('account_type').order('account_code').limit(500);tablePage('Profit & Loss Summary',data,error)}
async function backfillJournals(){if(!confirm('Create missing automatic journals for existing posted sales and purchases?'))return;const {data,error}=await sb.rpc('backfill_automatic_journals');if(error)return toast(error.message,'error');toast(`Backfill processed ${data?.processed||0} transaction(s)`);advancedReports()}
async function reports(){const {data,error}=await sb.from('v_daily_sales_summary').select('*').order('sale_date',{ascending:false}).limit(365);if(error)return tablePage('Sales Reports',data,error);$('#content').innerHTML=`<div class="section-head"><div><h2>Sales Reports</h2><div class="muted">Daily posted sales</div></div><button class="primary" onclick="advancedReports()">Advanced Dashboard</button></div>${renderTable(data,null)}`}
async function customerLedger(){const {data,error}=await sb.from('v_customer_ledger').select('customer_id,name,phone,transaction_type,reference_no,transaction_date,debit,credit,description').order('transaction_date',{ascending:false}).limit(1000);if(error)return tablePage('Customer Ledger',data,error);tablePage('Customer Ledger',data,null);}
async function supplierLedger(){const {data,error}=await sb.from('v_supplier_ledger').select('supplier_id,name,phone,transaction_type,reference_no,transaction_date,debit,credit,description').order('transaction_date',{ascending:false}).limit(1000);if(error)return tablePage('Supplier Ledger',data,error);tablePage('Supplier Ledger',data,null);}