(function(){
  const $=s=>document.querySelector(s);
  const sup=()=>window.supabaseClientForChoix||(window.supabaseClientForChoix=window.supabase.createClient("https://qahksphurzoojashjfyj.supabase.co","sb_publishable_zLxtcpAM-eTXRiV_8n8zrQ_PoZEp5pD"));
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const normalizeRole=r=>String(r||'').trim().toLowerCase();
  const roleCanEdit=r=>['owner','admin','manager'].includes(normalizeRole(r));
  let profile=null;
  const initials=n=>String(n||'U').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'U';
  async function loadProfile(){
    try{
      const {data:{user},error:authError}=await sup().auth.getUser();
      if(authError||!user)return false;
      const {data,error}=await sup().from('users').select('id,company_id,full_name,email,role_id,branch_id,roles(name)').eq('auth_user_id',user.id).single();
      if(error||!data)return false;
      profile=data;
      const {data:extra}=await sup().from('users').select('username,phone').eq('id',data.id).maybeSingle();
      if(extra)profile={...profile,...extra};
      return true;
    }catch(e){console.error('Profile load failed',e);return false}
  }
  function closeMenu(){const m=$('#profileMenu'),t=$('#profileTrigger');if(m)m.classList.add('hidden');if(t)t.setAttribute('aria-expanded','false')}
  function installHeader(){const host=$('#userInfo');if(!host)return false;if(host.dataset.profileUi==='1')return true;const raw=(host.textContent||'').trim(),parts=raw.split('·').map(x=>x.trim()),name=parts[0]||'User',role=parts[1]||'User';host.dataset.profileUi='1';host.className='profile-host';host.innerHTML=`<button id="profileTrigger" class="profile-trigger" type="button" aria-expanded="false"><span id="profileAvatar" class="profile-avatar">${esc(initials(name))}</span><span class="profile-summary"><b id="profileName">${esc(name)}</b><small id="profileRole">${esc(role)}</small></span><span class="profile-chevron">⌄</span></button><div id="profileMenu" class="profile-menu hidden"><button type="button" id="profileOpenBtn">Profile System</button><button type="button" id="passwordOpenBtn">Change Password</button><div class="profile-divider"></div><button type="button" id="profileLogoutBtn" class="profile-danger">Logout</button></div>`;const trigger=$('#profileTrigger'),menu=$('#profileMenu');trigger?.addEventListener('click',e=>{e.stopPropagation();const open=menu.classList.toggle('hidden')===false;trigger.setAttribute('aria-expanded',open?'true':'false')});$('#profileOpenBtn')?.addEventListener('click',()=>window.openProfileSystem());$('#passwordOpenBtn')?.addEventListener('click',()=>window.openProfileSystem('password'));$('#profileLogoutBtn')?.addEventListener('click',()=>$('#logout')?.click());document.addEventListener('click',e=>{if(!host.contains(e.target))closeMenu()});return true}
  function syncHeader(){if(!installHeader())return false;if(profile){const n=$('#profileName'),r=$('#profileRole'),a=$('#profileAvatar');if(n)n.textContent=profile.full_name||profile.email||'User';if(r)r.textContent=profile.roles?.name||'User';if(a)a.textContent=initials(profile.full_name||profile.email)}return true}
  async function branchLabel(){if(!profile?.branch_id)return 'Head Office / All';const {data}=await sup().from('branches').select('name').eq('id',profile.branch_id).maybeSingle();return data?.name||'Assigned Branch'}
  window.openProfileSystem=async function(mode){closeMenu();if(!profile)await loadProfile();if(!profile)return alert('Profile is still loading. Please refresh once.');if(mode==='password')return showPasswordModal();const editable=roleCanEdit(profile.roles?.name),branch=await branchLabel();const html=`<div class="profile-system-card"><div class="profile-hero"><div class="profile-avatar profile-avatar-lg">${esc(initials(profile.full_name||profile.email))}</div><div><h3>${esc(profile.full_name||'User')}</h3><p>${esc(profile.roles?.name||'User')} · ${esc(branch)}</p></div></div><form id="myProfileForm"><div class="form-grid"><label>Full Name<input id="my_full_name" value="${esc(profile.full_name||'')}" ${editable?'':'disabled'}></label><label>Username<input id="my_username" value="${esc(profile.username||'')}" ${editable?'':'disabled'}></label><label>Phone<input id="my_phone" value="${esc(profile.phone||'')}" ${editable?'':'disabled'}></label><label>Email<input value="${esc(profile.email||'')}" disabled></label><label>Role<input value="${esc(profile.roles?.name||'')}" disabled></label><label>Branch<input value="${esc(branch)}" disabled></label></div><p class="muted profile-note">${editable?'Owner, Admin and Manager can edit profile details.':'Branch users can view their profile but cannot edit controlled details.'}</p>${editable?'<button class="primary">Save Profile</button>':''}<button type="button" id="profileChangePassword">Change Password</button></form></div>`;if(typeof window.modal!=='function')return alert('Profile System is loading.');window.modal('Profile System',html);$('#myProfileForm')?.addEventListener('submit',async e=>{e.preventDefault();const {data,error}=await sup().rpc('update_my_profile',{p_full_name:$('#my_full_name')?.value||'',p_phone:$('#my_phone')?.value||'',p_username:$('#my_username')?.value||''});if(error)return alert(error.message);profile={...profile,...(data||{}),roles:profile.roles};window.closeModal?.();syncHeader();window.toast?.('Profile updated successfully')});$('#profileChangePassword')?.addEventListener('click',showPasswordModal)};
  function showPasswordModal(){if(typeof window.modal!=='function')return alert('Profile System is loading.');window.modal('Change Password','<form id="passwordForm"><label class="password-field"><input id="new_password" type="password" minlength="8" placeholder="New password" required><button type="button" data-target="new_password">Show</button></label><label class="password-field"><input id="new_password2" type="password" minlength="8" placeholder="Confirm new password" required><button type="button" data-target="new_password2">Show</button></label><button class="primary">Update Password</button></form>');document.querySelectorAll('.password-field button').forEach(b=>b.onclick=()=>{const i=$('#'+b.dataset.target);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Show':'Hide'});$('#passwordForm')?.addEventListener('submit',async e=>{e.preventDefault();const a=$('#new_password').value,b=$('#new_password2').value;if(a!==b)return alert('Passwords do not match.');const {error}=await sup().auth.updateUser({password:a});if(error)return alert(error.message);window.closeModal?.();alert('Password updated successfully.')})}
  async function usersPage(){
    if(!profile)await loadProfile();
    const role=String(profile?.roles?.name||'').trim();
    if(!profile){$('#content').innerHTML='<div class="card error"><h3>Profile could not be loaded</h3><p>Your login is valid, but the ERP profile could not be read. Please refresh once.</p></div>';return}
    if(!roleCanEdit(role)){$('#content').innerHTML='<div class="card error"><h3>Access denied</h3><p>Only Owner, Admin or Manager can manage users.</p></div>';return}
    const [{data:rows,error:ue},{data:roles,error:re},{data:branches,error:be}]=await Promise.all([sup().from('users').select('id,full_name,username,email,phone,is_active,created_at,branch_id,role_id,roles(name),branches(name)').eq('company_id',profile.company_id).order('created_at',{ascending:false}),sup().from('roles').select('id,name').eq('company_id',profile.company_id).order('name'),sup().from('branches').select('id,name').eq('company_id',profile.company_id).eq('is_active',true).order('name')]);
    if(ue||re||be){$('#content').innerHTML=`<div class="card error"><h3>Could not load Users & Roles</h3><p>${esc(ue?.message||re?.message||be?.message||'Could not load users')}</p></div>`;return}
    const all=rows||[], active=all.filter(u=>u.is_active).length, inactive=all.length-active, admins=all.filter(u=>['Owner','Admin','Manager'].includes(u.roles?.name)).length;
    const roleOpts=(roles||[]).filter(r=>normalizeRole(role)==='owner'||normalizeRole(r.name)!=='owner').map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('');
    const branchOpts=`<option value="">Head Office / All</option>`+(branches||[]).map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('');
    const table=all.map(u=>`<tr data-user-row="1"><td><div class="user-cell"><span class="user-row-avatar">${esc(initials(u.full_name||u.email))}</span><div><b>${esc(u.full_name||'Unnamed User')}</b><small>${esc(u.username||u.email||'')}</small></div></div></td><td>${esc(u.email||'')}</td><td><span class="role-badge role-${normalizeRole(u.roles?.name||'user')}">${esc(u.roles?.name||'User')}</span></td><td>${esc(u.branches?.name||'Head Office')}</td><td><span class="status-badge ${u.is_active?'active':'inactive'}"><i></i>${u.is_active?'Active':'Inactive'}</span></td><td>${esc(u.phone||'—')}</td></tr>`).join('');
    $('#content').innerHTML=`<div class="users-page"><div class="users-hero"><div><div class="eyebrow">ACCESS & TEAM</div><h2>Users & Roles</h2><p>Manage team accounts, roles and branch access from one secure workspace.</p></div><button class="primary users-add" id="addUserBtn">+ Add User</button></div><div class="user-metrics"><div><span>Total Users</span><strong>${all.length}</strong></div><div><span>Active</span><strong>${active}</strong></div><div><span>Inactive</span><strong>${inactive}</strong></div><div><span>Management Roles</span><strong>${admins}</strong></div></div><div class="users-toolbar"><div><h3>Team Members</h3><span class="muted">${all.length} account${all.length===1?'':'s'} in this company</span></div><input id="userSearch" class="user-filter" placeholder="Search name, email or role..."></div><div class="card users-table-card"><div class="table-scroll"><table class="table users-table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Branch</th><th>Status</th><th>Phone</th></tr></thead><tbody>${table||'<tr><td colspan="6" class="empty-users">No users found.</td></tr>'}</tbody></table></div></div></div>`;
    $('#userSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();document.querySelectorAll('[data-user-row="1"]').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')});
    $('#addUserBtn')?.addEventListener('click',()=>openAddUser(roleOpts,branchOpts));
  }
  function openAddUser(roleOpts,branchOpts){const html=`<form id="addUserForm"><div class="form-grid"><label>Full Name<input id="nu_name" required placeholder="User full name"></label><label>Username<input id="nu_username" placeholder="Username"></label><label>Email<input id="nu_email" type="email" required placeholder="user@example.com"></label><label>Phone<input id="nu_phone" placeholder="01XXXXXXXXX"></label><label>Password<div class="password-field"><input id="nu_password" type="password" minlength="6" required placeholder="Minimum 6 characters"><button type="button" data-target="nu_password">Show</button></div></label><label>Role<select id="nu_role" required>${roleOpts}</select></label><label>Branch<select id="nu_branch">${branchOpts}</select></label><label class="check-row"><input id="nu_active" type="checkbox" checked> Active user</label></div><p class="muted profile-note">The user will receive an active CHOIX ERP login immediately. Branch assignment controls which branch the user belongs to.</p><button class="primary" id="createUserBtn">Create User</button><div id="createUserMsg" class="muted" style="margin-top:10px"></div></form>`;window.modal('Add User',html);document.querySelectorAll('.password-field button').forEach(b=>b.onclick=()=>{const i=$('#'+b.dataset.target);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Show':'Hide'});$('#addUserForm')?.addEventListener('submit',createUser)}
  async function createUser(e){e.preventDefault();const btn=$('#createUserBtn'),msg=$('#createUserMsg');btn.disabled=true;msg.textContent='Creating login account...';const payload={full_name:$('#nu_name').value.trim(),username:$('#nu_username').value.trim(),email:$('#nu_email').value.trim(),phone:$('#nu_phone').value.trim(),password:$('#nu_password').value,role_id:$('#nu_role').value,branch_id:$('#nu_branch').value||null,is_active:$('#nu_active').checked};const {data,error}=await sup().functions.invoke('admin-create-user',{body:payload});if(error){btn.disabled=false;msg.textContent=data?.error||error.message;return}window.closeModal?.();window.toast?.('User created successfully');await usersPage()}
  window.users=usersPage;
  async function start(){await loadProfile();syncHeader()}
  start().catch(()=>{});
})();
